import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import vm from "node:vm";

const source = await readFile(new URL("../apps/workbench/public/design-004/design.js", import.meta.url), "utf8");
const control = (status = "difference") => ({ id:"ar-to-gl", label:"A/R snapshot to GL A/R", leftDefinition:"A/R snapshot", rightDefinition:"GL A/R", leftTotal:"566028", rightTotal:status === "matched" ? "566028" : "0", difference:status === "matched" ? "0" : "566028", arithmeticStatus:status, materialityStatus:"unset", evidence:["row:a"] });
async function render(finding) { let html=""; const events={}; const run={id:"run",dependencyFingerprint:"fp",profile:{id:"method",version:"1"},scope:{dealId:"TEST",currency:"USD"},gates:[{gate:"G3",status:"blocked"},{gate:"G7",status:"blocked"}],reconciliations:[control()],findings:finding?[finding]:[],sourceInventory:[],releaseRecords:[]}; const context={URLSearchParams,Intl,console,location:{search:"?run=run"},window:{scrollTo(){},alert(){}},document:{body:{classList:{toggle(){}}},getElementById(){return {set innerHTML(v){html=v},get innerHTML(){return html}}},querySelector(){return {focus(){}}},addEventListener(k,f){events[k]=f}},fetch:async()=>({ok:true,status:200,json:async()=>run})}; vm.runInNewContext(source,context); await new Promise(r=>setImmediate(r)); events.click({target:{closest(){return {dataset:{action:"lens:review"}}}}}); return html; }
test("D03 finding language follows authoritative finding status", async () => { const noFinding=await render(null); assert.match(noFinding,/Recorded reconciliation difference/); assert.doesNotMatch(noFinding,/>Open finding<\/span>/); const open=await render({id:"finding:ar-to-gl",status:"open",title:"A/R finding",detail:"open",references:["row:a"]}); assert.match(open,/>Open finding<\/span>/); const reviewed=await render({id:"finding:ar-to-gl",status:"reviewed",title:"A/R finding",detail:"reviewed",references:["row:a"]}); assert.match(reviewed,/Recorded finding · reviewed/); const resolved=await render({id:"finding:ar-to-gl",status:"resolved",title:"A/R finding",detail:"resolved",references:["row:a"]}); assert.match(resolved,/Recorded finding · resolved/); });
