import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname } from "node:path";
import { createHash, randomUUID } from "node:crypto";
import { analyze, compileWorkbook, createDecision, dependencyFingerprint, evaluateGates, inferMappings, invalidateStaleDecisions, ingestCsvSources, loadMethodProfile, reconcile, validateScope, xlsxToSourceFile } from "../../packages/core/dist/index.js";
import { loadRuns, saveRun } from "./store.mjs";

const runs = await loadRuns();
const profile = await loadMethodProfile(new URL("../../methodology/redwood-qor-v0.1.json", import.meta.url));
const json = (response, status, value) => { response.writeHead(status, { "content-type": "application/json" }); response.end(JSON.stringify(value, (_, item) => typeof item === "bigint" ? item.toString() : item)); };
const body = async (request) => { const chunks = []; for await (const chunk of request) chunks.push(chunk); return JSON.parse(Buffer.concat(chunks).toString("utf8")); };
const mime = { ".html": "text/html; charset=utf-8", ".js": "application/javascript; charset=utf-8", ".css": "text/css; charset=utf-8" };
function publicPath(pathname) { return pathname === "/" ? "index.html" : pathname.replace(/^\//, ""); }
function fingerprintFor(run) { const sourceHashes = [...new Set([...run.deal.claims, ...run.deal.cashEvents, ...run.deal.receivables, ...run.deal.glRecords].map((record) => record.lineage.sourceFileHash))].sort(); const mappingHash = createHash("sha256").update(JSON.stringify(run.mappings.map((mapping) => [mapping.id, mapping.reviewStatus, mapping.canonicalField]))).digest("hex"); const findingHash = createHash("sha256").update(JSON.stringify(run.findings.map((finding) => [finding.id, finding.status]))).digest("hex"); return dependencyFingerprint({ runId: run.id, methodVersion: run.profile.version, sourceHashes, mappingHash, assumptionHash: createHash("sha256").update(JSON.stringify(run.profile.recoveryRates)).digest("hex"), scopeHash: createHash("sha256").update(JSON.stringify(run.scope)).digest("hex"), engineVersion: "r1-v0.2", findingHash }); }

createServer(async (request, response) => {
  try {
    const url = new URL(request.url, "http://localhost");
    if (request.method === "GET" && url.pathname === "/api/method-profile") return json(response, 200, profile);
    if (request.method === "POST" && url.pathname === "/api/runs") {
      const input = await body(request); const candidates = input.files.filter((file) => ["claims", "payments", "adjustments", "ar_snapshot", "general_ledger"].includes(file.type) && typeof file.content === "string"); const accepted = await Promise.all(candidates.map((file) => file.format === "xlsx" ? xlsxToSourceFile({ name: file.name, type: file.type, content: Buffer.from(file.content, "base64"), worksheet: file.worksheet }) : file));
      const dealId = input.scope?.dealId ?? input.dealId ?? `ENG-${new Date().getFullYear()}`; const scope = validateScope({ dealId, valuationDate: input.scope?.valuationDate, analysisPeriodStart: input.scope?.analysisPeriodStart, analysisPeriodEnd: input.scope?.analysisPeriodEnd, currency: input.scope?.currency ?? "USD", entityScope: input.scope?.entityScope ?? ["Single entity / metadata-only"], methodProfileId: profile.id, methodVersion: profile.version }); const mappings = accepted.flatMap((file) => inferMappings(file, profile.version)); const deal = ingestCsvSources(dealId, accepted); const analysis = analyze(deal, profile, scope); const { reconciliations, findings } = reconcile(deal, profile, scope); const id = randomUUID(); const run = { id, scope, deal, analysis, reconciliations, findings, mappings, decisions: [], profile, createdAt: new Date().toISOString() }; run.dependencyFingerprint = fingerprintFor(run); run.gates = evaluateGates({ ...run, methodProfile: run.profile, dependencyFingerprint: run.dependencyFingerprint }); runs.set(id, run); await saveRun(run); return json(response, 201, run);
    }
    const mapping = url.pathname.match(/^\/api\/runs\/([^/]+)\/mappings\/([^/]+)\/approve$/);
    if (request.method === "POST" && mapping) { const run = runs.get(mapping[1]); if (!run) return json(response, 404, { error: "Analysis run not found" }); const input = await body(request); const record = run.mappings.find((item) => item.id === mapping[2]); if (!record) return json(response, 404, { error: "Mapping decision not found" }); if (!input.reviewer) return json(response, 400, { error: "Reviewer identity is required" }); record.reviewStatus = "approved"; record.reviewer = input.reviewer; record.timestamp = new Date().toISOString(); const previousFingerprint = run.dependencyFingerprint; run.dependencyFingerprint = fingerprintFor(run); run.decisions = invalidateStaleDecisions(run.decisions, run.dependencyFingerprint, previousFingerprint === run.dependencyFingerprint ? "Mapping review refreshed" : "Mapping state changed"); run.gates = evaluateGates({ ...run, methodProfile: run.profile, dependencyFingerprint: run.dependencyFingerprint }); await saveRun(run); return json(response, 200, record); }
    const decision = url.pathname.match(/^\/api\/runs\/([^/]+)\/decisions$/);
    if (request.method === "POST" && decision) { const run = runs.get(decision[1]); if (!run) return json(response, 404, { error: "Analysis run not found" }); const input = await body(request); const record = createDecision({ runId: run.id, methodProfileId: run.profile.id, methodVersion: run.profile.version, gate: input.gate, decision: input.decision, reviewer: input.reviewer, role: input.role, rationale: input.rationale, evidenceReferences: input.evidenceReferences ?? [], dependencyFingerprint: run.dependencyFingerprint }); run.decisions.push(record); run.gates = evaluateGates({ ...run, methodProfile: run.profile, dependencyFingerprint: run.dependencyFingerprint }); await saveRun(run); return json(response, 201, record); }
    const workbook = url.pathname.match(/^\/api\/runs\/([^/]+)\/workbook$/);
    if (request.method === "GET" && workbook) { const run = runs.get(workbook[1]); if (!run) return json(response, 404, { error: "Analysis run not found" }); const file = await compileWorkbook({ deal: run.deal, analysis: run.analysis, reconciliations: run.reconciliations, findings: run.findings, methodId: run.profile.id, methodVersion: run.profile.version, runId: run.id, scope: run.scope, methodProfile: run.profile, recoveryRates: run.profile.recoveryRates }); response.writeHead(200, { "content-type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "content-disposition": `attachment; filename=redwood-${run.id}.xlsx` }); return response.end(file); }
    const lookup = url.pathname.match(/^\/api\/runs\/([^/]+)$/);
    if (request.method === "GET" && lookup) { const run = runs.get(lookup[1]); return run ? json(response, 200, run) : json(response, 404, { error: "Analysis run not found" }); }
    if (request.method === "GET") { const path = publicPath(url.pathname); if (path.includes("..")) return json(response, 400, { error: "Invalid path" }); const content = await readFile(new URL(`./public/${path}`, import.meta.url)); response.writeHead(200, { "content-type": mime[extname(path)] || "application/octet-stream" }); return response.end(content); }
    json(response, 404, { error: "Not found" });
  } catch (error) { json(response, 400, { error: error instanceof Error ? error.message : "Unexpected error" }); }
}).listen(process.env.PORT || 4173, () => console.log(`Redwood Workbench: http://127.0.0.1:${process.env.PORT || 4173}`));
