import { sum } from "./money.js";
import type { CanonicalDeal, Cents, Claim, MethodProfile } from "./types.js";

export interface QorAnalysis { grossCharge: Cents; allowedAmount: Cents; observedCash: Cents; allocatedCollections: Cents; unappliedCash: Cents; subsequentCash: Cents; refunds: Cents; recoupments: Cents; transfers: Cents; openAr: Cents; arSnapshotDate?: string; adjustmentTotal: Cents; expectedRemainingCash: Cents; realizableRevenue: Cents; payerConcentration: Array<{ payer: string; observedCash: Cents }>; providerConcentration: Array<{ provider: string; grossCharge: Cents }>; locationConcentration: Array<{ location: string; grossCharge: Cents }>; serviceLineConcentration: Array<{ serviceLine: string; grossCharge: Cents }>; }
function group(items: Array<{ key?: string; amount?: Cents }>): Array<{ key: string; amount: Cents }> { const groups = new Map<string, Cents>(); for (const item of items) { const key = item.key ?? "Unavailable"; groups.set(key, (groups.get(key) ?? 0n) + (item.amount ?? 0n)); } return [...groups].map(([key, amount]) => ({ key, amount })).sort((a, b) => (a.amount > b.amount ? -1 : 1)); }
function activeClaims(claims: Claim[]): Claim[] { const superseded = new Set(claims.filter((claim) => claim.supersedesVersion !== undefined).map((claim) => `${claim.familyId}:${claim.supersedesVersion}`)); return claims.filter((claim) => !["voided", "superseded"].includes(claim.versionStatus) && !superseded.has(`${claim.familyId}:${claim.version}`)); }
/** Convert a configured decimal rate to an exact rational, then round half away from zero at the cent boundary. */
function applyRate(amount: Cents, rate: number): Cents { const text = String(rate); if (!/^\d+(\.\d+)?$/.test(text)) throw new Error(`Recovery rate must be a decimal literal: ${rate}`); const [whole, fractional = ""] = text.split("."); const denominator = 10n ** BigInt(fractional.length); const numerator = BigInt(whole + fractional); const negative = amount < 0n; const absolute = negative ? -amount : amount; const rounded = (absolute * numerator * 2n + denominator) / (2n * denominator); return negative ? -rounded : rounded; }
export function analyze(deal: CanonicalDeal, method: MethodProfile): QorAnalysis {
  const arSnapshotDate = [...new Set(deal.receivables.map((row) => row.snapshotDate))].sort().at(-1); const activeReceivables = arSnapshotDate ? deal.receivables.filter((row) => row.snapshotDate === arSnapshotDate) : []; const openAr = sum(activeReceivables.map((row) => row.balance)); let expectedRemainingCash = 0n; for (const item of activeReceivables) { const rate = method.recoveryRates[item.ageBucket ?? ""] ?? method.recoveryRates.global; if (rate !== undefined) expectedRemainingCash += applyRate(item.balance, rate); }
  const active = activeClaims(deal.claims); const allCash = sum(deal.cashEvents.map((event) => event.amount)); const unappliedCash = sum(deal.cashEvents.filter((event) => event.type === "unapplied_cash" || !event.claimId).map((event) => event.amount)); const refunds = sum(deal.cashEvents.filter((event) => event.type === "refund").map((event) => event.amount)); const recoupments = sum(deal.cashEvents.filter((event) => event.type === "recoupment").map((event) => event.amount)); const transfers = sum(deal.cashEvents.filter((event) => event.type === "transfer").map((event) => event.amount)); const allocatedCollections = sum(deal.cashEvents.filter((event) => event.claimId && event.type !== "unapplied_cash" && event.type !== "transfer" && active.some((claim) => claim.id === event.claimId)).map((event) => event.amount));
  return { arSnapshotDate, grossCharge: sum(active.map((claim) => claim.grossCharge)), allowedAmount: sum(active.map((claim) => claim.allowedAmount)), observedCash: allCash, allocatedCollections, unappliedCash, subsequentCash: 0n, refunds, recoupments, transfers, openAr, adjustmentTotal: sum(deal.adjustmentEvents.map((event) => event.amount)), expectedRemainingCash, realizableRevenue: allocatedCollections + expectedRemainingCash, payerConcentration: group(deal.cashEvents.filter((event) => event.claimId && event.type !== "unapplied_cash").map((event) => ({ key: event.payer, amount: event.amount }))).map((x) => ({ payer: x.key, observedCash: x.amount })), providerConcentration: group(active.map((claim) => ({ key: claim.provider, amount: claim.grossCharge }))).map((x) => ({ provider: x.key, grossCharge: x.amount })), locationConcentration: group(active.map((claim) => ({ key: claim.location, amount: claim.grossCharge }))).map((x) => ({ location: x.key, grossCharge: x.amount })), serviceLineConcentration: group(active.map((claim) => ({ key: claim.serviceLine, amount: claim.grossCharge }))).map((x) => ({ serviceLine: x.key, grossCharge: x.amount })) };
}
