import assert from "node:assert/strict";
import test from "node:test";
import ExcelJS from "exceljs";
import { readFile } from "node:fs/promises";
import { analyze, compareGoldDealMetrics, compileWorkbook, createDecision, dependencyFingerprint, deriveReceivableAge, evaluateGates, ingestCsvSources, invalidateDecision, loadMethodProfile, isActiveDecision, parseMoney, reconcile, xlsxToSourceFile, type Gate, type MappingDecision, type MethodProfile } from "./index.js";

const method: MethodProfile = { id: "redwood-draft", name: "Redwood Draft", version: "0.1.0", status: "engineering-hypothesis-not-professionally-approved", arithmeticToleranceCents: 1n, ageingBasis: "service_date", recoveryMethod: "age_bucket_rates", recoveryRates: { "0-30": 0.8, "121+": 0.1 } };
const files = [
  { name: "claims.csv", type: "claims" as const, content: "claim_id,service_date,billed,allowed,provider,service_line\nC1,2026-06-01,100.00,75.00,Dr A,Office\nC2,2026-06-02,50.00,40.00,Dr B,Lab" },
  { name: "payments.csv", type: "payments" as const, content: "payment_id,claim_id,payment_date,amount,payer\nP1,C1,2026-06-10,60.00,Medicare\nP2,,2026-06-11,($5.00),Refund" },
  { name: "ar.csv", type: "ar_snapshot" as const, content: "receivable_id,snapshot_date,balance,age_bucket\nC1,2026-06-30,15.00,0-30\nC2,2026-06-30,20.00,121+" },
  { name: "gl.csv", type: "general_ledger" as const, content: "period,cash,ar\n2026-06,50.00,40.00" }
];
test("money preserves blanks and parenthesized negatives", () => { assert.equal(parseMoney(""), undefined); assert.equal(parseMoney("($321.45)"), -32145n); assert.throws(() => parseMoney("not money")); });
test("ingestion preserves differences rather than forcing controls", () => { const deal = ingestCsvSources("ENG001", files); const { reconciliations, findings } = reconcile(deal, method); assert.equal(deal.quarantined.length, 0); assert.equal(reconciliations.find((x) => x.id === "all-cash-to-gl")?.difference, 500n); assert.ok(findings.some((f) => f.id === "finding:unmatched-cash")); });
test("recovery changes expected cash but not observed cash", () => { const deal = ingestCsvSources("ENG001", files); const low = analyze(deal, method); const high = analyze(deal, { ...method, recoveryRates: { "0-30": 0.9, "121+": 0.9 } }); assert.equal(low.observedCash, high.observedCash); assert.notEqual(low.expectedRemainingCash, high.expectedRemainingCash); });
test("compiler creates formula-driven xlsx with traceability", async () => { const deal = ingestCsvSources("ENG001", files); const analysis = analyze(deal, method); const { reconciliations, findings } = reconcile(deal, method); const output = await compileWorkbook({ deal, analysis, reconciliations, findings, methodId: method.id, methodVersion: method.version, runId: "run-1", recoveryRates: method.recoveryRates }); const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(output); ["Executive Summary", "QoR Waterfall", "Cash Collections", "AR Aging", "Payer Analysis", "Location Analysis", "Provider Analysis", "Service Line", "Recovery Analysis", "Assumptions", "Findings", "Source Trace"].forEach((name) => assert.ok(workbook.getWorksheet(name), `Missing ${name}`)); assert.equal(workbook.getWorksheet("Executive Summary")?.getCell("B13").formula, "SUM('Recovery Analysis'!D2:D6)"); assert.equal(workbook.getWorksheet("Executive Summary")?.getCell("B14").formula, "B9+B13"); assert.ok(workbook.getWorksheet("Source Trace")?.getColumn(4).values.includes("GLRecord")); assert.equal(workbook.getWorksheet("Reconciliation")?.getCell("D2").formula, "B2-C2"); });
test("XLSX adapter preserves worksheet strings for canonical ingestion", async () => { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("AR"); sheet.addRows([["receivable_id", "snapshot_date", "balance"], ["A1", "2026-06-30", "($12.34)"]]); const source = await xlsxToSourceFile({ name: "ar.xlsx", type: "ar_snapshot", content: Buffer.from(await workbook.xlsx.writeBuffer()), worksheet: "AR" }); const deal = ingestCsvSources("ENG001", [source]); assert.equal(deal.receivables[0].balance, -1234n); });
test("claim versions and typed adjustments remain distinct canonical events", () => { const deal = ingestCsvSources("ENG002", [{ name: "claims.csv", type: "claims", content: "claim_id,claim_version,service_date,billed\nC1,1,2026-06-01,100.00\nC1,2,2026-06-01,120.00" }, { name: "adjustments.csv", type: "adjustments", content: "adjustment_id,claim_id,adjustment_type,posting_date,amount\nA1,C1,write_off,2026-06-02,($20.00)" }]); assert.equal(deal.claims.length, 2); assert.equal(deal.adjustmentEvents.length, 1); assert.equal(analyze(deal, method).adjustmentTotal, -2000n); });
test("ENG002 keeps variants and does not silently aggregate A/R snapshots", async () => { const root = new URL("../../../fixtures/eng002/", import.meta.url); const file = async (name, type) => ({ name, type, content: await readFile(new URL(name, root), "utf8") }); const deal = ingestCsvSources("ENG002", await Promise.all([file("claims.csv", "claims"), file("payments.csv", "payments"), file("adjustments.csv", "adjustments"), file("ar_snapshot.csv", "ar_snapshot"), file("general_ledger.csv", "general_ledger")])); const analysis = analyze(deal, method); const result = reconcile(deal, method); assert.equal(deal.claims.length, 4); assert.equal(deal.adjustmentEvents.length, 3); assert.equal(analysis.arSnapshotDate, "2026-04-30"); assert.equal(analysis.openAr, 6500n); assert.equal(analysis.grossCharge, 62000n); assert.ok(result.findings.some((finding) => finding.id === "finding:mixed-ar-snapshots")); });
test("release gates block unresolved reconciliation even when a workbook is available", () => { const deal = ingestCsvSources("ENG001", files); const { reconciliations, findings } = reconcile(deal, method); const gates = evaluateGates({ deal, mappings: [], reconciliations, findings, decisions: [] }); assert.equal(gates.find((gate) => gate.gate === "G3")?.status, "blocked"); assert.equal(gates.find((gate) => gate.gate === "G7")?.status, "blocked"); });
test("PHI-exclusion policy quarantines disallowed direct identifiers", () => { const deal = ingestCsvSources("ENG-PHI", [{ name: "claims.csv", type: "claims", content: "claim_id,patient_name,billed\nC1,Jane Doe,100.00" }]); assert.equal(deal.claims.length, 0); assert.match(deal.quarantined[0].reason, /PHI-exclusion policy/); });
test("Gold Deal validation matrix preserves unavailable values and differences", () => { const matrix = compareGoldDealMetrics([{ metric: "Observed cash", professionalValue: 10000n, redwoodValue: 9900n, reviewStatus: "open" }, { metric: "QoR adjustment", professionalValue: 500n, reviewStatus: "open" }]); assert.equal(matrix[0].difference, -100n); assert.equal(matrix[1].difference, undefined); });
test("an upstream change invalidates a run-bound professional decision", () => { const decision = createDecision({ runId: "run-1", methodProfileId: method.id, methodVersion: method.version, gate: "G5", decision: "approved", reviewer: "Advisor", role: "Partner", rationale: "Reviewed recovery basis.", evidenceReferences: [] }); assert.ok(isActiveDecision(decision, "run-1", method.version)); const invalidated = invalidateDecision(decision, "Recovery assumption changed"); assert.equal(isActiveDecision(invalidated, "run-1", method.version), false); assert.match(invalidated.invalidationReason ?? "", /changed/); });
test("approval dependency fingerprint invalidates after mapping or source changes", () => { const base = { runId: "run-1", methodVersion: method.version, sourceHashes: ["source-a"], mappingHash: "mapping-a", assumptionHash: "assumption-a", scopeHash: "scope-a", engineVersion: "r1", findingHash: "findings-a" }; const fingerprint = dependencyFingerprint(base); const decision = createDecision({ runId: "run-1", methodProfileId: method.id, methodVersion: method.version, gate: "G7", decision: "approved", reviewer: "Advisor", role: "Partner", rationale: "Release basis reviewed.", evidenceReferences: [], dependencyFingerprint: fingerprint }); assert.ok(isActiveDecision(decision, "run-1", method.version, fingerprint)); assert.equal(isActiveDecision(decision, "run-1", method.version, dependencyFingerprint({ ...base, mappingHash: "mapping-b" })), false); assert.equal(isActiveDecision(decision, "run-1", method.version, dependencyFingerprint({ ...base, sourceHashes: ["source-b"] })), false); });
test("recovery cents use exact rational arithmetic rather than binary money math", () => { const deal = ingestCsvSources("ENG-RATE", [{ name: "ar.csv", type: "ar_snapshot", content: "receivable_id,snapshot_date,balance,age_bucket\nA1,2026-06-30,1.00,0-30" }]); const result = analyze(deal, { ...method, recoveryRates: { "0-30": 0.333 } }); assert.equal(result.expectedRemainingCash, 33n); });
test("valuation cutoff keeps subsequent cash out of observed collections", () => { const deal = ingestCsvSources("CUT", [{ name: "claims.csv", type: "claims", content: "claim_id,service_date,billed\nC1,2026-06-01,100.00\nC2,2026-07-01,100.00" }, { name: "payments.csv", type: "payments", content: "payment_id,claim_id,payment_date,amount\nP1,C1,2026-06-30,50.00\nP2,C1,2026-07-02,10.00" }, { name: "ar.csv", type: "ar_snapshot", content: "receivable_id,snapshot_date,balance,age_bucket\nC1,2026-06-30,50.00,0-30" }]); const scope = { dealId: "CUT", valuationDate: "2026-06-30", analysisPeriodStart: "2026-01-01", analysisPeriodEnd: "2026-06-30", currency: "USD", entityScope: ["Target"], methodProfileId: method.id, methodVersion: method.version }; const result = analyze(deal, method, scope); assert.equal(result.grossCharge, 10000n); assert.equal(result.allocatedCollections, 5000n); assert.equal(result.subsequentCash, 1000n); });
test("A/R ageing derives inclusive boundary buckets and preserves day zero", () => { const scope = { dealId: "AGE", valuationDate: "2026-05-01", analysisPeriodStart: "2026-01-01", analysisPeriodEnd: "2026-05-01", currency: "USD", entityScope: ["Target"], methodProfileId: method.id, methodVersion: method.version }; const cases: Array<[string, number, string]> = [["2026-05-01", 0, "0-30"], ["2026-04-01", 30, "0-30"], ["2026-03-31", 31, "31-60"], ["2026-03-02", 60, "31-60"], ["2026-03-01", 61, "61-90"], ["2026-01-31", 90, "61-90"], ["2026-01-30", 91, "91-120"], ["2026-01-01", 120, "91-120"], ["2025-12-31", 121, "121+"]]; for (const [date, days, bucket] of cases) { const deal = ingestCsvSources("AGE", [{ name: "claims.csv", type: "claims", content: `claim_id,service_date\nC1,${date}` }, { name: "ar.csv", type: "ar_snapshot", content: "receivable_id,claim_id,snapshot_date,balance\nC1,C1,2026-05-01,1.00" }]); const result = deriveReceivableAge(deal.receivables[0], deal.claims[0], scope, method); assert.equal(result?.ageDays, days); assert.equal(result?.ageBucket, bucket); } });
test("runtime loads draft and synthetic scenario profiles without hidden recovery defaults", async () => { const draft = await loadMethodProfile(new URL("../../../methodology/redwood-qor-v0.1.json", import.meta.url)); const scenario = await loadMethodProfile(new URL("../../../methodology/synthetic-demo-scenario-v0.1.json", import.meta.url)); assert.equal(draft.recoveryRates["0-30"], undefined); assert.equal(draft.status, "engineering-hypothesis-not-professionally-approved"); assert.equal(scenario.status, "synthetic-testing-only"); assert.equal(scenario.recoveryRates["0-30"], 0.9); });
test("execution mapping set drives canonical claim amount", () => { const mappings = [{ id: "m1", sourceType: "claims" as const, sourceField: "Alternate_Billed", canonicalField: "gross_charge", confidence: 1, mappingRule: "reviewed test", evidence: "test", methodVersion: method.version, reviewStatus: "approved" as const, reviewer: "Reviewer", timestamp: "2026-01-01" }]; const deal = ingestCsvSources("MAP", [{ name: "claims.csv", type: "claims", content: "Claim_ID,DOS,Billed_Amount,Alternate_Billed\nC1,2026-06-01,100.00,125.00" }], mappings); assert.equal(deal.claims[0].grossCharge, 12500n); });
test("Payment_Type maps patient and unapplied cash semantics", () => { const deal = ingestCsvSources("PAY", [{ name: "payments.csv", type: "payments", content: "Payment_ID,Claim_ID,Payment_Date,Payment_Type,Paid_Amount\nP1,C1,2026-06-01,Patient Payment,10.00\nP2,,2026-06-01,Unapplied Cash,5.00" }]); assert.equal(deal.cashEvents[0].type, "patient_payment"); assert.equal(deal.cashEvents[1].type, "unapplied_cash"); });
test("G7 cannot bypass any individually blocked prerequisite", () => { const deal = ingestCsvSources("GATES", files); const mappings: MappingDecision[] = ["claims", "payments", "ar_snapshot", "general_ledger"].map((sourceType, index) => ({ id: String(index), sourceType: sourceType as MappingDecision["sourceType"], sourceField: "id", canonicalField: "id", confidence: 1, mappingRule: "test", evidence: "test", methodVersion: method.version, reviewStatus: "approved", reviewer: "Reviewer", timestamp: "2026-01-01" })); const decisions = (["G0", "G5", "G6", "G7"] as Gate[]).map((gate) => ({ id: gate, runId: "run", methodProfileId: method.id, methodVersion: method.version, gate, decision: "approved" as const, reviewer: "Reviewer", role: "Partner", rationale: "test", evidenceReferences: [], timestamp: "2026-01-01" })); const matched = { id: "r", label: "r", leftDefinition: "l", rightDefinition: "r", leftTotal: 0n, rightTotal: 0n, difference: 0n, arithmeticStatus: "matched" as const, materialityStatus: "unset" as const, evidence: [] }; const base = { deal, mappings, reconciliations: [matched], findings: [], decisions }; assert.equal(evaluateGates(base).find((gate) => gate.gate === "G7")?.status, "passed"); const cases = [ { ...base, decisions: decisions.filter((d) => d.gate !== "G0") }, { ...base, mappings: mappings.map((m, i) => i === 0 ? { ...m, reviewStatus: "proposed" as const } : m) }, { ...base, reconciliations: [{ ...matched, arithmeticStatus: "difference" as const }] }, { ...base, calculationPassed: false }, { ...base, decisions: decisions.filter((d) => d.gate !== "G5") }, { ...base, findings: [{ id: "f", kind: "reconciliation" as const, title: "f", detail: "f", status: "open" as const, references: [] }] } ]; cases.forEach((input) => assert.equal(evaluateGates(input).find((gate) => gate.gate === "G7")?.status, "blocked")); });
