import assert from "node:assert/strict";
import test from "node:test";
import ExcelJS from "exceljs";
import { readFile } from "node:fs/promises";
import { analyze, compareGoldDealMetrics, compileWorkbook, evaluateGates, ingestCsvSources, parseMoney, reconcile, xlsxToSourceFile, type MethodProfile } from "./index.js";

const method: MethodProfile = { id: "redwood-draft", name: "Redwood Draft", version: "0.1.0", status: "engineering-hypothesis-not-professionally-approved", arithmeticToleranceCents: 1n, ageingBasis: "service_date", recoveryMethod: "age_bucket_rates", recoveryRates: { "0-30": 0.8, "121+": 0.1 } };
const files = [
  { name: "claims.csv", type: "claims" as const, content: "claim_id,service_date,billed,allowed,provider,service_line\nC1,2026-06-01,100.00,75.00,Dr A,Office\nC2,2026-06-02,50.00,40.00,Dr B,Lab" },
  { name: "payments.csv", type: "payments" as const, content: "payment_id,claim_id,payment_date,amount,payer\nP1,C1,2026-06-10,60.00,Medicare\nP2,,2026-06-11,($5.00),Refund" },
  { name: "ar.csv", type: "ar_snapshot" as const, content: "receivable_id,snapshot_date,balance,age_bucket\nC1,2026-06-30,15.00,0-30\nC2,2026-06-30,20.00,121+" },
  { name: "gl.csv", type: "general_ledger" as const, content: "period,cash,ar\n2026-06,50.00,40.00" }
];
test("money preserves blanks and parenthesized negatives", () => { assert.equal(parseMoney(""), undefined); assert.equal(parseMoney("($321.45)"), -32145n); assert.throws(() => parseMoney("not money")); });
test("ingestion preserves differences rather than forcing controls", () => { const deal = ingestCsvSources("ENG001", files); const { reconciliations, findings } = reconcile(deal, method); assert.equal(deal.quarantined.length, 0); assert.equal(reconciliations.find((x) => x.id === "all-cash-to-gl")?.difference, 500n); assert.ok(findings.some((f) => f.id === "finding:unmatched-cash")); });
test("recovery changes expected cash but not observed cash", () => { const deal = ingestCsvSources("ENG001", files); const low = analyze(deal, method); const high = analyze(deal, { ...method, recoveryRates: { "0-30": 0.9, "121+": 0.9 } }); assert.equal(low.observedCash, high.observedCash); assert.notEqual(low.expectedRemainingCash, high.expectedRemainingCash); });
test("compiler creates formula-driven xlsx with traceability", async () => { const deal = ingestCsvSources("ENG001", files); const analysis = analyze(deal, method); const { reconciliations, findings } = reconcile(deal, method); const output = await compileWorkbook({ deal, analysis, reconciliations, findings, methodId: method.id, methodVersion: method.version, runId: "run-1", recoveryRates: method.recoveryRates }); const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(output); ["Executive Summary", "QoR Waterfall", "Cash Collections", "AR Aging", "Payer Analysis", "Location Analysis", "Provider Analysis", "Service Line", "Collection Curves", "Assumptions", "Findings", "Source Trace"].forEach((name) => assert.ok(workbook.getWorksheet(name), `Missing ${name}`)); assert.equal(workbook.getWorksheet("Executive Summary")?.getCell("B10").formula, "SUM('Collection Curves'!D2:D6)"); assert.equal(workbook.getWorksheet("Executive Summary")?.getCell("B11").formula, "B8+B10"); assert.equal(workbook.getWorksheet("Reconciliation")?.getCell("D2").formula, "B2-C2"); });
test("XLSX adapter preserves worksheet strings for canonical ingestion", async () => { const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("AR"); sheet.addRows([["receivable_id", "snapshot_date", "balance"], ["A1", "2026-06-30", "($12.34)"]]); const source = await xlsxToSourceFile({ name: "ar.xlsx", type: "ar_snapshot", content: Buffer.from(await workbook.xlsx.writeBuffer()), worksheet: "AR" }); const deal = ingestCsvSources("ENG001", [source]); assert.equal(deal.receivables[0].balance, -1234n); });
test("claim versions and typed adjustments remain distinct canonical events", () => { const deal = ingestCsvSources("ENG002", [{ name: "claims.csv", type: "claims", content: "claim_id,claim_version,service_date,billed\nC1,1,2026-06-01,100.00\nC1,2,2026-06-01,120.00" }, { name: "adjustments.csv", type: "adjustments", content: "adjustment_id,claim_id,adjustment_type,posting_date,amount\nA1,C1,write_off,2026-06-02,($20.00)" }]); assert.equal(deal.claims.length, 2); assert.equal(deal.adjustmentEvents.length, 1); assert.equal(analyze(deal, method).adjustmentTotal, -2000n); });
test("ENG002 keeps variants and does not silently aggregate A/R snapshots", async () => { const root = new URL("../../../fixtures/eng002/", import.meta.url); const file = async (name, type) => ({ name, type, content: await readFile(new URL(name, root), "utf8") }); const deal = ingestCsvSources("ENG002", await Promise.all([file("claims.csv", "claims"), file("payments.csv", "payments"), file("adjustments.csv", "adjustments"), file("ar_snapshot.csv", "ar_snapshot"), file("general_ledger.csv", "general_ledger")])); const analysis = analyze(deal, method); const result = reconcile(deal, method); assert.equal(deal.claims.length, 4); assert.equal(deal.adjustmentEvents.length, 3); assert.equal(analysis.arSnapshotDate, "2026-04-30"); assert.equal(analysis.openAr, 6500n); assert.ok(result.findings.some((finding) => finding.id === "finding:mixed-ar-snapshots")); });
test("release gates block unresolved reconciliation even when a workbook is available", () => { const deal = ingestCsvSources("ENG001", files); const { reconciliations, findings } = reconcile(deal, method); const gates = evaluateGates({ deal, mappings: [], reconciliations, findings, decisions: [] }); assert.equal(gates.find((gate) => gate.gate === "G3")?.status, "blocked"); assert.equal(gates.find((gate) => gate.gate === "G7")?.status, "blocked"); });
test("PHI-exclusion policy quarantines disallowed direct identifiers", () => { const deal = ingestCsvSources("ENG-PHI", [{ name: "claims.csv", type: "claims", content: "claim_id,patient_name,billed\nC1,Jane Doe,100.00" }]); assert.equal(deal.claims.length, 0); assert.match(deal.quarantined[0].reason, /PHI-exclusion policy/); });
test("Gold Deal validation matrix preserves unavailable values and differences", () => { const matrix = compareGoldDealMetrics([{ metric: "Observed cash", professionalValue: 10000n, redwoodValue: 9900n, reviewStatus: "open" }, { metric: "QoR adjustment", professionalValue: 500n, reviewStatus: "open" }]); assert.equal(matrix[0].difference, -100n); assert.equal(matrix[1].difference, undefined); });
