import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import { join } from "node:path";
import ExcelJS from "exceljs";
import { analyze, deriveReceivableAge, ingestCsvSources, parseCsv, reconcile, xlsxToSourceFile, loadMethodProfile } from "./index.js";
const workbookPath = process.env.ENG001_FULL_XLSX ?? join(process.cwd(), "../../.tmp/eng001-full-raw.xlsx");
const bytes = await readFile(workbookPath); const workbookHash = createHash("sha256").update(bytes).digest("hex");
const sheet = async (name: string, type: "claims"|"payments"|"ar_snapshot"|"general_ledger") => xlsxToSourceFile({ name: `ENG001_FULL:${name}`, type, content: bytes, worksheet: name });
// Validation_Truth is deliberately not opened before the independent engine run below.
const [claims, payments, ar, gl] = await Promise.all([sheet("Claims_Raw", "claims"), sheet("Payments_Raw", "payments"), sheet("AR_Snapshot_Raw", "ar_snapshot"), sheet("GL_Monthly_Raw", "general_ledger")]);
const paymentRows = parseCsv(payments.content); const adjustmentRows = paymentRows.flatMap((row, index) => [["contractual_adjustment", row.Contractual_Adjustment], ["denial", row.Denial_Adjustment]].filter(([, value]) => value && value !== "0" && value !== "0.00").map(([type, amount]) => ({ adjustment_id: `ENG001-PAY-${index + 2}-${type}`, claim_id: row.Claim_ID, adjustment_type: type, posting_date: row.Payment_Date, amount, payer: row.Payer_Raw })));
const adjustmentHeaders = "adjustment_id,claim_id,adjustment_type,posting_date,amount,payer"; const adjustments = { name: "ENG001_FULL:Payments_Raw:adjustments", type: "adjustments" as const, content: [adjustmentHeaders, ...adjustmentRows.map((row) => Object.values(row).map((value) => `\"${String(value).replaceAll('\"', '\"\"')}\"`).join(","))].join("\n") };
const profile = await loadMethodProfile(join(process.cwd(), "../../methodology/synthetic-demo-scenario-v0.1.json")); const scope = { dealId: "ENG001_FULL", valuationDate: "2026-06-30", analysisPeriodStart: "2025-01-01", analysisPeriodEnd: "2026-06-30", currency: "USD", entityScope: ["Synthetic Physician Group"], methodProfileId: profile.id, methodVersion: profile.version };
const deal = ingestCsvSources(scope.dealId, [claims, payments, ar, gl, adjustments]); const analysis = analyze(deal, profile, scope); const result = reconcile(deal, profile, scope);
const engine = { Claim_Count: deal.claims.length, Total_Billed: Number(analysis.grossCharge) / 100, Total_Expected_Allowed: Number(analysis.allowedAmount) / 100, Matched_Total_Paid: Number(analysis.allocatedCollections) / 100, Unmatched_Payment: Number(analysis.unappliedCash) / 100, Open_AR_2026_06_30: Number(analysis.openAr) / 100, AR_120_Plus: Number(deal.receivables.filter((r) => r.snapshotDate === "2026-06-30" && deriveReceivableAge(r, deal.claims.find((claim) => claim.id === r.claimId), scope, profile)?.ageBucket === "121+").reduce((total, row) => total + row.balance, 0n)) / 100, Denied_Open_Claim_Count: deal.receivables.filter((r) => r.snapshotDate === "2026-06-30" && String(r.lineage.raw.Status ?? "").toLowerCase().includes("denied")).length, Known_GL_Cash_Variance_June_2026: Math.abs(Number(result.reconciliations.find((r) => r.id === "all-cash-to-gl")?.difference ?? 0n) / 100), Expected_Review_Gate: result.findings.some((f) => f.id === "finding:all-cash-to-gl") ? "G3_RECONCILIATION_EXCEPTION" : "UNEXPECTED" };
// Only after the engine result exists do we open Validation_Truth for comparison.
const truthBook = new ExcelJS.Workbook(); const workbookBytes = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; await truthBook.xlsx.load(workbookBytes); const truthSheet = truthBook.getWorksheet("Validation_Truth")!; const truth = new Map<string, number | string>(); truthSheet.eachRow((row, index) => { if (index > 1) truth.set(String(row.getCell(1).value), row.getCell(2).value as number | string); }); const comparison = [...truth.entries()].map(([metric, expected]) => ({ metric, expected, actual: engine[metric as keyof typeof engine], matches: typeof expected === "number" ? Math.abs(Number(engine[metric as keyof typeof engine]) - expected) <= 0.01 : engine[metric as keyof typeof engine] === expected }));
const evidence = { sourceDocumentId: "1Wc9cCo-mCt7LmMvNqVn0hP-yUdM58SHXfFcsV4e8lMg", workbookHash, sheets: ["Claims_Raw", "Payments_Raw", "AR_Snapshot_Raw", "GL_Monthly_Raw"], counts: { claims: deal.claims.length, payments: deal.cashEvents.length, receivables: deal.receivables.length, adjustments: deal.adjustmentEvents.length, quarantined: deal.quarantined.length }, engine, comparison, findings: result.findings.map((f) => f.id) }; await mkdir(join(process.cwd(), "../../artifacts"), { recursive: true }); await writeFile(join(process.cwd(), "../../artifacts/eng001-full-integration.json"), JSON.stringify(evidence, null, 2)); console.log(JSON.stringify(evidence, null, 2));
