import { sha256 } from "./hash.js";
import { parseCsv, stableRowId, type CsvRow } from "./csv.js";
import { parseTsv } from "./tsv.js";
import { parseMoney } from "./money.js";
import { normalizeLegacyCashRow, normalizeLegacyChargeRow, normalizeNewCashRow, normalizeNewChargeRow, parseMigrationCrosswalk, resolveMigrationProvider, type MigrationCrosswalk } from "./migration.js";
import type { AdjustmentEvent, CanonicalDeal, CashEvent, Claim, GLRecord, LineageRecord, MappingDecision, MigrationContribution, MigrationCrosswalkCoverage, QuarantineRecord, Receivable, SourceType } from "./types.js";

export interface SourceFile { name: string; type: SourceType; content: string; }
const migrationSourceTypes = new Set<SourceType>(["legacy_pm_charges", "rcm_new_charges", "legacy_cash", "new_cash"]);
const field = (row: CsvRow, names: string[]) => names.map((name) => row[name]).find((value) => value !== undefined);
const validDate = (value: string | undefined) => !value || /^\d{4}-\d{2}-\d{2}$/.test(value) || /^\d{4}-\d{2}$/.test(value);
function classifyCashType(value: string | undefined): CashEvent["type"] { const normalized = (value ?? "").toLowerCase(); if (normalized.includes("unapplied")) return "unapplied_cash"; if (normalized.includes("patient")) return "patient_payment"; if (normalized.includes("refund")) return "refund"; if (normalized.includes("recoup")) return "recoupment"; if (normalized.includes("transfer")) return "transfer"; if (normalized.includes("secondary")) return "secondary_payer_payment"; return "payer_payment"; }
const forbiddenPhiHeaders = new Set(["patient_name", "patient name", "first_name", "last_name", "ssn", "social_security_number", "street_address", "address", "clinical_note", "clinical narrative"]);
function lineage(file: SourceFile, hash: string, index: number, raw: CsvRow): LineageRecord { return { sourceFileHash: hash, sourceFileName: file.name, sourceRowId: stableRowId(hash, index + 2), raw }; }
function unique<T extends { id: string }>(items: T[], item: T, type: SourceType, quarantine: QuarantineRecord): void { if (items.some((candidate) => candidate.id === item.id)) throw Object.assign(new Error("duplicate"), { quarantine }); items.push(item); }
function migrationContribution(file: SourceFile, hash: string): MigrationContribution { const sourceSystem = file.type === "legacy_pm_charges" || file.type === "legacy_cash" ? "LEGACY_PM" : "NEW_RCM"; return { sourceType: file.type as MigrationContribution["sourceType"], sourceSystem, sourceFileName: file.name, sourceFileHash: hash, inputRows: 0, acceptedRows: 0, quarantinedRows: 0, grossCharge: 0n, cash: 0n }; }

/**
 * Converts source rows into the canonical deal without collapsing native PM/RCM schemas.
 * Native migration classifications are accepted only through the explicit provider-key crosswalk.
 */
export function ingestCsvSources(dealId: string, files: SourceFile[], mappingSet: MappingDecision[] = []): CanonicalDeal {
  const mappedField = (raw: CsvRow, sourceType: SourceType, canonical: string, fallback: string[]) => { const decision = mappingSet.find((item) => item.sourceType === sourceType && item.canonicalField === canonical); if (mappingSet.length > 0) return decision && decision.reviewStatus !== "rejected" ? raw[decision.sourceField] : undefined; return field(raw, fallback); };
  const deal: CanonicalDeal = { dealId, claims: [], cashEvents: [], adjustmentEvents: [], receivables: [], glRecords: [], bankDeposits: [], providerRoster: [], serviceLineHistory: [], payerContractReferences: [], ownershipSiteHistory: [], quarantined: [] };
  const nativeFiles = files.filter((file) => migrationSourceTypes.has(file.type));
  let crosswalk: MigrationCrosswalk[] = [];
  let crosswalkFile: SourceFile | undefined;
  let crosswalkFailure: string | undefined;
  const crosswalkFiles = files.filter((file) => file.type === "migration_crosswalk");
  if (nativeFiles.length) {
    if (crosswalkFiles.length !== 1) crosswalkFailure = crosswalkFiles.length ? "Exactly one migration crosswalk file is required" : "Missing migration crosswalk file";
    else { crosswalkFile = crosswalkFiles[0]; try { crosswalk = parseMigrationCrosswalk(crosswalkFile.content); } catch (error) { crosswalkFailure = error instanceof Error ? error.message : "Invalid migration crosswalk"; } }
    deal.migrationEvidence = { crosswalkFileName: crosswalkFile?.name, crosswalkFileHash: crosswalkFile ? sha256(crosswalkFile.content) : undefined, crosswalkEntries: crosswalk.length, contributions: [], crosswalkCoverage: [] };
  }
  const coverageProviders: Record<"LEGACY_PM" | "NEW_RCM", Set<string>> = { LEGACY_PM: new Set(), NEW_RCM: new Set() };
  const coverageMissing: Record<"LEGACY_PM" | "NEW_RCM", Set<string>> = { LEGACY_PM: new Set(), NEW_RCM: new Set() };
  const seenHashes = new Set<string>();
  for (const file of files) {
    const hash = sha256(file.content);
    if (seenHashes.has(hash)) { deal.quarantined.push({ sourceType: file.type, sourceRowId: `${hash}:file`, reason: "Duplicate file content", raw: {} }); continue; }
    seenHashes.add(hash);
    if (file.type === "migration_crosswalk") continue;
    let rows: CsvRow[];
    try { rows = file.type === "new_cash" ? parseTsv(file.content) : parseCsv(file.content); } catch (error) { deal.quarantined.push({ sourceType: file.type, sourceRowId: `${hash}:file`, reason: error instanceof Error ? error.message : "Invalid delimited source", raw: {} }); continue; }
    const headers = rows[0] ? Object.keys(rows[0]).map((header) => header.trim().toLowerCase()) : []; const forbidden = headers.filter((header) => forbiddenPhiHeaders.has(header)); if (forbidden.length) { deal.quarantined.push({ sourceType: file.type, sourceRowId: `${hash}:file`, reason: `PHI-exclusion policy blocked headers: ${forbidden.join(", ")}`, raw: {} }); continue; }
    const contribution = migrationSourceTypes.has(file.type) ? migrationContribution(file, hash) : undefined;
    if (contribution) deal.migrationEvidence!.contributions.push(contribution);
    rows.forEach((raw, index) => {
      const sourceRowId = stableRowId(hash, index + 2); const base = lineage(file, hash, index, raw);
      if (contribution) contribution.inputRows++;
      try {
        if (migrationSourceTypes.has(file.type)) {
          if (crosswalkFailure) throw new Error(crosswalkFailure);
          if (file.type === "legacy_pm_charges" || file.type === "rcm_new_charges") {
            const sourceSystem = file.type === "legacy_pm_charges" ? "LEGACY_PM" : "NEW_RCM";
            const sourceProviderId = file.type === "legacy_pm_charges" ? raw.rendering_provider : raw.ProviderKey;
            if (sourceProviderId) { coverageProviders[sourceSystem].add(sourceProviderId); try { resolveMigrationProvider(crosswalk, sourceSystem, sourceProviderId); } catch { coverageMissing[sourceSystem].add(sourceProviderId); } }
            const migrated = file.type === "legacy_pm_charges" ? normalizeLegacyChargeRow(raw, crosswalk, file.name) : normalizeNewChargeRow(raw, crosswalk, file.name);
            const match = resolveMigrationProvider(crosswalk, migrated.sourceSystem, migrated.sourceProviderId);
            const claim: Claim = { id: migrated.id, familyId: migrated.id, version: 1, versionStatus: "original", serviceDate: migrated.serviceDate, payer: migrated.payer, provider: migrated.provider, location: migrated.location, serviceLine: migrated.serviceLine, grossCharge: migrated.grossCharge, allowedAmount: migrated.allowedAmount, lineage: { ...base, sourceSystem: migrated.sourceSystem, crosswalk: { sourceSystem: match.sourceSystem, sourceProviderId: match.sourceProviderId, canonicalProviderId: match.canonicalProviderId, crosswalkSourceRow: match.sourceRowNumber } } };
            if (deal.claims.some((candidate) => candidate.id === claim.id && candidate.version === claim.version)) throw new Error("Duplicate claim/version"); deal.claims.push(claim); contribution!.grossCharge += claim.grossCharge ?? 0n;
          } else {
            const migrated = file.type === "legacy_cash" ? normalizeLegacyCashRow(raw, file.name) : normalizeNewCashRow(raw, file.name);
            const cash: CashEvent = { id: migrated.id, claimId: migrated.claimId, type: classifyCashType(migrated.sourceEventType), sourceEventType: migrated.sourceEventType, amount: migrated.amount, paymentDate: migrated.paymentDate, payer: migrated.payer, lineage: { ...base, sourceSystem: migrated.sourceSystem } };
            unique(deal.cashEvents, cash, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate payment ID", raw }); contribution!.cash += cash.amount;
          }
          contribution!.acceptedRows++;
        } else if (file.type === "claims") {
          const id = mappedField(raw, file.type, "claim_id", ["claim_id", "Claim_ID", "Claim ID"]); if (!id) throw new Error("Missing claim ID");
          const serviceDate = mappedField(raw, file.type, "service_date", ["service_date", "DOS", "Date of Service"]); if (!validDate(serviceDate)) throw new Error("Invalid service date");
          const version = Number(field(raw, ["claim_version", "Claim_Version"]) ?? "1"); const versionStatus = (field(raw, ["version_status", "claim_status", "Version_Status"]) as Claim["versionStatus"]) ?? "original"; const supersedes = field(raw, ["supersedes_version", "Supersedes_Version"]); const claim: Claim = { id, familyId: field(raw, ["claim_family_id", "Claim_Family_ID"]) ?? id, version, versionStatus, supersedesVersion: supersedes === undefined || supersedes === "" ? undefined : Number(supersedes), serviceDate, submissionDate: field(raw, ["claim_submission_date", "submission_date"]), payer: mappedField(raw, file.type, "payer", ["payer", "Primary_Insurance"]), provider: mappedField(raw, file.type, "provider", ["provider", "Provider_ID"]), location: mappedField(raw, file.type, "location", ["location", "Location", "Location_ID"]), serviceLine: mappedField(raw, file.type, "service_line", ["service_line", "Service_Line"]), grossCharge: parseMoney(mappedField(raw, file.type, "gross_charge", ["gross_charge", "billed", "Billed", "Billed_Amount"])), allowedAmount: parseMoney(mappedField(raw, file.type, "allowed_amount", ["allowed_amount", "allowed", "Allowed", "Expected_Allowed_Amount"])), patientResponsibility: parseMoney(field(raw, ["patient_responsibility", "Patient_Responsibility", "PatientShare", "pt_resp"])), reportedRevenue: parseMoney(field(raw, ["reported_revenue", "revenue"])), lineage: base };
          if (deal.claims.some((candidate) => candidate.id === claim.id && candidate.version === claim.version)) throw new Error("Duplicate claim/version"); deal.claims.push(claim);
        } else if (file.type === "payments") {
          const id = mappedField(raw, file.type, "payment_id", ["payment_id", "Payment_ID", "Payment ID"]); if (!id) throw new Error("Missing payment ID"); const amount = parseMoney(mappedField(raw, file.type, "cash_amount", ["amount", "paid_amount", "Amt Paid", "Paid_Amount"])); if (amount === undefined) throw new Error("Missing payment amount"); const paymentDate = mappedField(raw, file.type, "payment_date", ["payment_date", "Payment_Date"]); if (!validDate(paymentDate)) throw new Error("Invalid payment date"); const sourceEventType = mappedField(raw, file.type, "payment_type", ["cash_event_type", "event_type", "type", "Payment_Type"]); const cash: CashEvent = { id, claimId: mappedField(raw, file.type, "claim_id", ["claim_id", "Claim_ID"]), type: classifyCashType(sourceEventType), sourceEventType, amount, paymentDate, payer: mappedField(raw, file.type, "payer", ["payer", "Payer", "Payer_Raw"]), lineage: base }; unique(deal.cashEvents, cash, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate payment ID", raw });
        } else if (file.type === "adjustments") {
          const id = field(raw, ["adjustment_id", "Adjustment_ID", "Adjustment ID"]); if (!id) throw new Error("Missing adjustment ID"); const amount = parseMoney(field(raw, ["amount", "adjustment_amount", "Amt"])); if (amount === undefined) throw new Error("Missing adjustment amount"); const postingDate = field(raw, ["posting_date", "Posting_Date"]); if (!validDate(postingDate)) throw new Error("Invalid adjustment posting date"); const adjustment: AdjustmentEvent = { id, claimId: field(raw, ["claim_id", "Claim_ID"]), type: (field(raw, ["adjustment_type", "type"]) as AdjustmentEvent["type"]) ?? "other", amount, postingDate, payer: field(raw, ["payer", "Payer"]), lineage: base }; unique(deal.adjustmentEvents, adjustment, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate adjustment ID", raw });
        } else if (file.type === "provider_roster") {
          const providerId = field(raw, ["provider_id", "Provider_ID"]); if (!providerId) throw new Error("Missing provider ID"); const fteText = field(raw, ["fte", "FTE"]); const entry = { providerId, fte: fteText === undefined || fteText === "" ? undefined : Number(fteText), startDate: field(raw, ["start_date", "Start_Date"]), endDate: field(raw, ["end_date", "End_Date"]), specialty: field(raw, ["specialty", "Specialty"]), lineage: base }; unique(deal.providerRoster, { id: providerId, ...entry }, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate provider roster ID", raw });
        } else if (file.type === "service_line_history") { const serviceLine = field(raw, ["service_line", "Service_Line"]); const eventText = field(raw, ["event", "Event"])?.toLowerCase(); const effectiveDate = field(raw, ["effective_date", "Effective_Date"]); if (!serviceLine || !effectiveDate || !validDate(effectiveDate)) throw new Error("Missing service-line history fields"); const event = eventText === "new_service_expansion" ? "new_service_expansion" : eventText === "service_discontinuation" ? "service_discontinuation" : "other"; unique(deal.serviceLineHistory, { id: `${serviceLine}:${effectiveDate}:${event}`, serviceLine, event, effectiveDate, lineage: base }, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate service-line history event", raw });
        } else if (file.type === "payer_contract_reference") { const payer = field(raw,["payer","Payer"]); const periodStart=field(raw,["period_start","Period_Start"]); const periodEnd=field(raw,["period_end","Period_End"]); const indexValue=Number(field(raw,["relative_rate_index","Relative_Rate_Index"])); if(!payer||!periodStart||!validDate(periodStart)||!Number.isFinite(indexValue)) throw new Error("Missing payer contract reference fields"); unique(deal.payerContractReferences,{id:`${payer}:${periodStart}`,payer,periodStart,periodEnd:periodEnd||undefined,relativeRateIndex:indexValue,status:field(raw,["status","Status"]),lineage:base},file.type,{sourceType:file.type,sourceRowId,reason:"Duplicate payer contract reference",raw});
        } else if (file.type === "ownership_site_history") { const locationId=field(raw,["location_id","Location_ID"]); const eventText=field(raw,["event","Event"])?.toLowerCase(); const effectiveDate=field(raw,["effective_date","Effective_Date"]); if(!locationId||!effectiveDate||!validDate(effectiveDate)) throw new Error("Missing ownership-site history fields"); const event=eventText==="acquired_site"?"acquired_site":"other"; unique(deal.ownershipSiteHistory,{id:`${locationId}:${effectiveDate}:${event}`,locationId,event,effectiveDate,classification:field(raw,["classification","Classification"]),notes:field(raw,["notes","Notes"]),lineage:base},file.type,{sourceType:file.type,sourceRowId,reason:"Duplicate ownership-site history event",raw});
        } else if (file.type === "bank_deposits") { const id = field(raw, ["deposit_id", "Deposit_ID"]); const amount = parseMoney(field(raw, ["amount", "Amount"])); const depositDate = field(raw, ["deposit_date", "Deposit_Date"]); if (!id || amount === undefined) throw new Error("Missing bank deposit ID or amount"); if (!validDate(depositDate)) throw new Error("Invalid bank deposit date"); unique(deal.bankDeposits, { id, depositDate, amount, lineage: base }, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate bank deposit ID", raw });
        } else if (file.type === "ar_snapshot") { const id = field(raw, ["receivable_id", "ar_id", "Claim_ID", "claim_id"]); const snapshotDate = mappedField(raw, file.type, "snapshot_date", ["snapshot_date", "Snapshot_Date"]); const balance = parseMoney(mappedField(raw, file.type, "ar_balance", ["balance", "open_ar", "Open AR", "Open_AR"])); if (!id || !snapshotDate || balance === undefined) throw new Error("Missing receivable ID, snapshot date, or balance"); if (!validDate(snapshotDate)) throw new Error("Invalid A/R snapshot date"); const receivable: Receivable = { id: `${id}:${snapshotDate}`, claimId: field(raw, ["claim_id", "Claim_ID"]) ?? id, snapshotDate, balance, ageBasis: (field(raw, ["age_basis"]) as Receivable["ageBasis"]) ?? "service_date", ageDays: Number(field(raw, ["age_days", "Age_Days"]) ?? "") || undefined, ageBucket: field(raw, ["age_bucket", "Age_Bucket"]), payer: mappedField(raw, file.type, "payer", ["payer", "Payer", "Payer_Raw"]), provider: mappedField(raw, file.type, "provider", ["provider", "Provider_ID"]), location: mappedField(raw, file.type, "location", ["location", "Location", "Location_ID"]), serviceLine: mappedField(raw, file.type, "service_line", ["service_line", "Service_Line"]), lineage: base }; unique(deal.receivables, receivable, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate receivable snapshot row", raw });
        } else { const period = mappedField(raw, file.type, "accounting_period", ["period", "Month", "month"]); if (!period) throw new Error("Missing GL period"); const payerCash = parseMoney(field(raw, ["Payer_Cash_Collections"])); const patientCash = parseMoney(field(raw, ["Patient_Collections"])); const accountCash = String(field(raw, ["account", "Account"]) ?? "").toLowerCase().includes("cash") ? parseMoney(field(raw, ["amount", "Amount"])) : undefined; const record: GLRecord = { id: field(raw, ["gl_id", "GL_ID"]) ?? `${period}:${index + 2}`, period, netPatientRevenue: parseMoney(field(raw, ["net_patient_revenue", "revenue", "Net_Patient_Revenue"])), cash: parseMoney(field(raw, ["cash", "gl_cash"])) ?? accountCash ?? (payerCash === undefined && patientCash === undefined ? undefined : (payerCash ?? 0n) + (patientCash ?? 0n)), matchedCash: parseMoney(field(raw, ["matched_cash", "gl_matched_cash"])), ar: parseMoney(mappedField(raw, file.type, "gl_ar", ["ar", "gl_ar", "Ending_AR_Model"])), badDebt: parseMoney(field(raw, ["bad_debt", "GL Bad Debt"])), lineage: base }; unique(deal.glRecords, record, file.type, { sourceType: file.type, sourceRowId, reason: "Duplicate GL record", raw }); }
      } catch (error) { if (contribution) contribution.quarantinedRows++; deal.quarantined.push({ sourceType: file.type, sourceRowId, reason: error instanceof Error ? error.message : "Invalid row", raw }); }
    });
  }
  if (deal.migrationEvidence) {
    const coverage: MigrationCrosswalkCoverage[] = (["LEGACY_PM", "NEW_RCM"] as const).map((sourceSystem) => { const providers = coverageProviders[sourceSystem]; const missing = coverageMissing[sourceSystem]; return { sourceSystem, sourceProviders: providers.size, mappedProviders: providers.size - missing.size, missingProviderIds: [...missing].sort() }; });
    deal.migrationEvidence.crosswalkCoverage = coverage;
  }
  return deal;
}
