import { randomUUID } from "node:crypto";
import { parseCsv } from "./csv.js";
import type { SourceFile } from "./ingest.js";
import type { MappingDecision, SourceType } from "./types.js";

const aliases: Record<string, string[]> = { claim_id: ["claim_id", "Claim_ID", "Claim ID"], claim_version: ["claim_version", "Claim_Version"], service_date: ["service_date", "DOS", "Date of Service"], gross_charge: ["gross_charge", "billed", "Billed"], allowed_amount: ["allowed_amount", "allowed", "Allowed"], payment_id: ["payment_id", "Payment_ID", "Payment ID"], payment_date: ["payment_date", "Payment_Date"], cash_amount: ["amount", "paid_amount", "Amt Paid"], snapshot_date: ["snapshot_date", "Snapshot_Date"], ar_balance: ["balance", "open_ar", "Open AR"], accounting_period: ["period", "Month", "month"], gl_cash: ["cash", "gl_cash"], gl_ar: ["ar", "gl_ar"], adjustment_id: ["adjustment_id", "Adjustment_ID", "Adjustment ID"], adjustment_amount: ["adjustment_amount", "Amt"] };
export interface SourcePreview { sourceType: SourceType; headers: string[]; rowCount: number; sampleRows: Record<string, string>[]; }
export function previewSource(source: SourceFile): SourcePreview { const rows = parseCsv(source.content); return { sourceType: source.type, headers: rows[0] ? Object.keys(rows[0]) : [], rowCount: rows.length, sampleRows: rows.slice(0, 5) }; }
export function inferMappings(source: SourceFile, methodVersion: string): MappingDecision[] { const preview = previewSource(source); return preview.headers.map((header) => { const canonicalField = Object.entries(aliases).find(([, names]) => names.includes(header))?.[0]; return { id: randomUUID(), sourceType: source.type, sourceField: header, canonicalField, confidence: canonicalField ? 1 : 0, mappingRule: canonicalField ? "exact configured source-header alias" : "no configured alias", evidence: `${source.name}: header ${header}`, methodVersion, reviewStatus: "proposed", timestamp: new Date().toISOString() }; }); }
