import { sum } from "./money.js";
import type { CanonicalDeal, CashEvent, Claim, Cents, DealScope } from "./types.js";

export type CoverageState = "comparable" | "partial" | "immature" | "absent" | "not_applicable";
export type ProfessionalTreatmentState = "evidence_only" | "review_required" | "reviewed" | "approved_for_normalization" | "rejected";
export interface ComparisonWindow { start: string; end: string; dateField: "service_date" | "payment_date"; }
export interface Coverage { state: CoverageState; datedRowCount: number; undatedRowCount: number; reason?: string; }
export interface PeriodMetrics { billed: Cents; allowed: Cents; claimCount: number; realizedCash: Cents; patientCash: Cents; payerCash: Cents; patientResponsibility?: Cents; openPatientBalance?: Cents; coverage: Coverage; lineageRefs: string[]; }
export interface SustainabilityRow { id: string; current: PeriodMetrics; prior?: PeriodMetrics; change?: Cents; growth?: number; mixShareCurrent?: number; mixSharePrior?: number; mixChange?: number; effectiveReimbursementCurrent?: number; effectiveReimbursementPrior?: number; volumeEffect?: Cents; mixEffect?: Cents; effectiveRateEffect?: Cents; residual?: Cents; coverage: CoverageState; evidenceState: ProfessionalTreatmentState; limitation?: string; event?: { type: string; effectiveDate: string; classification?: string }; }
export interface RevenueSustainabilityAnalysis { comparison: { current: ComparisonWindow; prior?: ComparisonWindow; coverage: CoverageState; limitation?: string }; provider: SustainabilityRow[]; payer: SustainabilityRow[]; serviceLine: SustainabilityRow[]; location: SustainabilityRow[]; patientResponsibility: SustainabilityRow[]; cashBuckets: Array<{ bucket: "payer" | "patient" | "other_cash" | "unapplied" | "unattributed"; amount: Cents; eventCount: number }>; }
const inWindow = (date: string | undefined, window: ComparisonWindow) => !!date && date >= window.start && date <= window.end;
const refs = (items: Array<{ lineage: { sourceRowId: string } }>) => items.map(x => x.lineage.sourceRowId).sort();
const coverage = (items: Claim[], window: ComparisonWindow): Coverage => { const dated = items.filter(x => !!x.serviceDate); const count = dated.filter(x => inWindow(x.serviceDate, window)).length; const undated = items.length - dated.length; return { state: count ? "comparable" : "immature", datedRowCount: count, undatedRowCount: undated, ...(undated ? { reason: "Undated source rows excluded from dated comparison." } : {}) }; };
const active = (claims: Claim[]) => { const superseded = new Set(claims.filter(c => c.supersedesVersion !== undefined).map(c => `${c.familyId}:${c.supersedesVersion}`)); return claims.filter(c => !["voided", "superseded"].includes(c.versionStatus) && !superseded.has(`${c.familyId}:${c.version}`)); };
function period(claims: Claim[], cash: CashEvent[], window: ComparisonWindow): PeriodMetrics { const rows = claims.filter(c => inWindow(c.serviceDate, window)); const ids = new Set(rows.map(c => c.id)); const events = cash.filter(e => inWindow(e.paymentDate, { ...window, dateField: "payment_date" }) && !!e.claimId && ids.has(e.claimId)); const patient = events.filter(e => e.type === "patient_payment"); const payer = events.filter(e => e.type === "payer_payment" || e.type === "secondary_payer_payment"); return { billed: sum(rows.map(c => c.grossCharge)), allowed: sum(rows.map(c => c.allowedAmount)), claimCount: rows.length, realizedCash: sum(events.map(e => e.amount)), patientCash: sum(patient.map(e => e.amount)), payerCash: sum(payer.map(e => e.amount)), coverage: coverage(claims, window), lineageRefs: refs(rows) }; }
function row(id: string, current: PeriodMetrics, prior: PeriodMetrics | undefined, totalCurrent: Cents, totalPrior: Cents, event?: SustainabilityRow["event"]): SustainabilityRow { if (!prior) return { id, current, coverage: "absent", evidenceState: "evidence_only", limitation: "Prior comparable window was not supplied.", event }; const comparable = current.coverage.state === "comparable" && prior.coverage.state === "comparable"; const change = current.allowed - prior.allowed; const growth = comparable && prior.allowed !== 0n ? Number(change) / Math.abs(Number(prior.allowed)) : undefined; const shareC = totalCurrent ? Number(current.allowed) / Number(totalCurrent) : undefined; const shareP = totalPrior ? Number(prior.allowed) / Number(totalPrior) : undefined; const rateC = current.claimCount ? Number(current.allowed) / current.claimCount : undefined; const rateP = prior.claimCount ? Number(prior.allowed) / prior.claimCount : undefined; const volume = comparable && shareP !== undefined && rateP !== undefined ? BigInt(Math.round((current.claimCount - prior.claimCount) * shareP * rateP)) : undefined; const mix = comparable && shareP !== undefined && shareC !== undefined && rateP !== undefined ? BigInt(Math.round(current.claimCount * (shareC - shareP) * rateP)) : undefined; const rate = comparable && shareC !== undefined && rateC !== undefined && rateP !== undefined ? BigInt(Math.round(current.claimCount * shareC * (rateC - rateP))) : undefined; const residual = volume === undefined || mix === undefined || rate === undefined ? undefined : change - volume - mix - rate; return { id, current, prior, change, growth, mixShareCurrent: shareC, mixSharePrior: shareP, mixChange: shareC === undefined || shareP === undefined ? undefined : shareC - shareP, effectiveReimbursementCurrent: rateC, effectiveReimbursementPrior: rateP, volumeEffect: volume, mixEffect: mix, effectiveRateEffect: rate, residual, coverage: comparable ? "comparable" : "partial", evidenceState: event ? "review_required" : "evidence_only", ...(comparable ? {} : { limitation: "Comparison coverage is incomplete or immature; percentage movement is withheld." }), event }; }
export function analyzeRevenueSustainability(deal: CanonicalDeal, scope?: DealScope): RevenueSustainabilityAnalysis { if (!scope) return { comparison: { current: { start: "Unavailable", end: "Unavailable", dateField: "service_date" }, coverage: "absent", limitation: "Scoped comparison window unavailable." }, provider: [], payer: [], serviceLine: [], location: [], patientResponsibility: [], cashBuckets: [] }; const current: ComparisonWindow = { start: scope.analysisPeriodStart, end: scope.analysisPeriodEnd, dateField: "service_date" }; const prior = scope.priorComparableStart && scope.priorComparableEnd ? { start: scope.priorComparableStart, end: scope.priorComparableEnd, dateField: "service_date" as const } : undefined; const claims = active(deal.claims).filter(c => !c.serviceDate || c.serviceDate <= scope.valuationDate); const cash = deal.cashEvents.filter(e => !e.paymentDate || e.paymentDate <= scope.valuationDate); const totalC = period(claims, cash, current).allowed; const totalP = prior ? period(claims, cash, prior).allowed : 0n; const dimension = (key: (c: Claim) => string | undefined, events: Array<{ id: string; effectiveDate: string; classification?: string }> = []) => { const keys = new Set(claims.map(c => key(c) ?? "Unavailable")); return [...keys].sort().map(id => { const subset = claims.filter(c => (key(c) ?? "Unavailable") === id); const event = events.find(x => x.id === id); return row(id, period(subset, cash, current), prior ? period(subset, cash, prior) : undefined, totalC, totalP, event ? { type: event.classification ?? "event", effectiveDate: event.effectiveDate, classification: event.classification } : undefined); }); };
 const provider = dimension(c => c.provider).map(item => { const roster = deal.providerRoster.find(r => r.providerId === item.id); const departureDate = roster?.endDate; if (!departureDate || departureDate >= scope.valuationDate) return item; const pre = claims.filter(c => c.provider === item.id && c.serviceDate && c.serviceDate <= departureDate); const post = claims.filter(c => c.provider === item.id && c.serviceDate && c.serviceDate > departureDate); return { ...item, event: { type: "provider_departure", effectiveDate: departureDate }, evidenceState: post.length ? "review_required" as const : "evidence_only" as const, current: { ...item.current, lineageRefs: [...item.current.lineageRefs, ...refs(pre), ...refs(post)].sort() } }; });
 const payer = dimension(c => c.payer); const serviceLine = dimension(c => c.serviceLine, deal.serviceLineHistory.map(e => ({ id: e.serviceLine, effectiveDate: e.effectiveDate, classification: e.event }))); const location = dimension(c => c.location, deal.ownershipSiteHistory.map(e => ({ id: e.locationId, effectiveDate: e.effectiveDate, classification: e.event })));
 const patientCurrentClaims = claims.filter(c => inWindow(c.serviceDate, current) && c.patientResponsibility !== undefined); const patientPriorClaims = prior ? claims.filter(c => inWindow(c.serviceDate, prior) && c.patientResponsibility !== undefined) : []; const patientCurrentBase = period(claims, cash, current); const patientPriorBase = prior ? period(claims, cash, prior) : undefined; const patientCurrent: PeriodMetrics = { ...patientCurrentBase, billed: sum(patientCurrentClaims.map(c => c.patientResponsibility)), allowed: sum(patientCurrentClaims.map(c => c.patientResponsibility)), patientResponsibility: sum(patientCurrentClaims.map(c => c.patientResponsibility)), lineageRefs: refs(patientCurrentClaims) }; const patientPrior: PeriodMetrics | undefined = patientPriorBase && prior ? { ...patientPriorBase, billed: sum(patientPriorClaims.map(c => c.patientResponsibility)), allowed: sum(patientPriorClaims.map(c => c.patientResponsibility)), patientResponsibility: sum(patientPriorClaims.map(c => c.patientResponsibility)), lineageRefs: refs(patientPriorClaims) } : undefined; const patientResponsibility: SustainabilityRow[] = patientCurrentClaims.length || patientPriorClaims.length ? [row("Patient responsibility", patientCurrent, patientPrior, patientCurrent.allowed, patientPrior?.allowed ?? 0n)] : [];
 const buckets = new Map<string, { bucket: "payer" | "patient" | "other_cash" | "unapplied" | "unattributed"; amount: Cents; eventCount: number }>(); for (const event of cash.filter(e => inWindow(e.paymentDate, { ...current, dateField: "payment_date" }))) { const linked = event.claimId && claims.some(c => c.id === event.claimId); const bucket = !linked || event.type === "unapplied_cash" ? "unapplied" : event.type === "patient_payment" ? "patient" : event.type === "payer_payment" || event.type === "secondary_payer_payment" ? "payer" : ["refund", "recoupment", "reversal", "replacement_payment", "transfer"].includes(event.type) ? "other_cash" : "unattributed"; const entry = buckets.get(bucket) ?? { bucket, amount: 0n, eventCount: 0 }; entry.amount += event.amount; entry.eventCount++; buckets.set(bucket, entry); }
 return { comparison: { current, prior, coverage: prior ? "comparable" : "absent", ...(prior ? {} : { limitation: "Prior comparable window was not supplied." }) }, provider, payer, serviceLine, location, patientResponsibility, cashBuckets: [...buckets.values()].sort((a,b) => a.bucket.localeCompare(b.bucket)) }; }
