import ExcelJS from "exceljs";
import { money } from "./money.js";
import type { QorAnalysis } from "./analytics.js";
import type { CanonicalDeal, DealScope, Finding, MethodProfile, Reconciliation } from "./types.js";
import { deriveReceivableAge } from "./ageing.js";

function style(workbook: ExcelJS.Workbook): void { for (const sheet of workbook.worksheets) { sheet.views = [{ state: "frozen", ySplit: 1 }]; sheet.getRow(1).font = { bold: true, color: { argb: "FF102B36" } }; sheet.columns.forEach((column) => { column.width = Math.max(column.width ?? 10, 18); }); } }
function moneyColumn(sheet: ExcelJS.Worksheet, column: number): void { sheet.getColumn(column).numFmt = '$#,##0.00;[Red]-$#,##0.00'; }

export async function compileWorkbook(input: { deal: CanonicalDeal; analysis: QorAnalysis; reconciliations: Reconciliation[]; findings: Finding[]; methodId: string; methodVersion: string; runId: string; scope?: DealScope; methodProfile?: MethodProfile; recoveryRates?: Record<string, number | undefined> }): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook(); workbook.creator = "Redwood"; workbook.properties.date1904 = false;
  const summary = workbook.addWorksheet("Executive Summary"); summary.addRows([["Redwood Quality of Revenue Databook"], ["Run ID", input.runId], ["Method", `${input.methodId} ${input.methodVersion}`], [], ["Metric", "Value"], ["Gross charge", Number(input.analysis.grossCharge) / 100], ["Allowed amount", Number(input.analysis.allowedAmount) / 100], ["All cash", Number(input.analysis.observedCash) / 100], ["Allocated collections", Number(input.analysis.allocatedCollections) / 100], ["Unapplied cash", Number(input.analysis.unappliedCash) / 100], ["Subsequent cash", Number(input.analysis.subsequentCash) / 100], ["Open A/R", Number(input.analysis.openAr) / 100], ["Expected remaining cash", null], ["Realizable revenue", null]]); summary.getCell("B13").value = { formula: "SUM('Recovery Analysis'!D2:D6)" }; summary.getCell("B14").value = { formula: "B9+B13" }; moneyColumn(summary, 2); summary.getColumn(1).width = 30; summary.getColumn(2).width = 24;
  const waterfall = workbook.addWorksheet("QoR Waterfall"); waterfall.addRows([["Metric", "Amount"], ["Gross charge", null], ["Allowed amount", null], ["Observed cash", null], ["Expected remaining cash", null], ["Realizable revenue", null]]); ["'Executive Summary'!B6", "'Executive Summary'!B7", "'Executive Summary'!B9", "'Executive Summary'!B13", "B4+B5"].forEach((formula, index) => { waterfall.getCell(`B${index + 2}`).value = { formula }; }); moneyColumn(waterfall, 2);
  const cash = workbook.addWorksheet("Cash Collections"); cash.addRow(["Cash event ID", "Claim ID", "Type", "Payment date", "Payer", "Amount"]); input.deal.cashEvents.forEach((event) => cash.addRow([event.id, event.claimId ?? "", event.type, event.paymentDate ?? "", event.payer ?? "", Number(event.amount) / 100])); moneyColumn(cash, 6);
  const activeSnapshotDate = input.scope?.valuationDate ?? [...new Set(input.deal.receivables.map((item) => item.snapshotDate))].sort().at(-1); const aging = workbook.addWorksheet("AR Aging"); aging.addRow(["Receivable ID", "Snapshot", "Claim ID", "Age basis", "Source age days", "Source age bucket", "Redwood age days", "Redwood age bucket", "Age validation", "Balance", "Valuation snapshot"]); input.deal.receivables.forEach((item) => { const derived = input.scope && input.methodProfile ? deriveReceivableAge(item, input.deal.claims.find((claim) => claim.id === item.claimId), input.scope, input.methodProfile) : undefined; const validation = derived ? (derived.ageDays === item.ageDays && derived.ageBucket === item.ageBucket ? "Matches source" : "Differs from source") : "Unavailable"; aging.addRow([item.id, item.snapshotDate, item.claimId ?? "", item.ageBasis, item.ageDays ?? "Unavailable", item.ageBucket ?? "Unavailable", derived?.ageDays ?? "Unavailable", derived?.ageBucket ?? "Unavailable", validation, Number(item.balance) / 100, item.snapshotDate === activeSnapshotDate ? "Active" : "Historical"]); }); moneyColumn(aging, 10);
  const payer = workbook.addWorksheet("Payer Analysis"); payer.addRow(["Payer", "Observed cash"]); input.analysis.payerConcentration.forEach((item) => payer.addRow([item.payer, Number(item.observedCash) / 100])); moneyColumn(payer, 2);
  const location = workbook.addWorksheet("Location Analysis"); location.addRow(["Location", "Gross charge"]); input.analysis.locationConcentration.forEach((item) => location.addRow([item.location, Number(item.grossCharge) / 100])); moneyColumn(location, 2);
  const provider = workbook.addWorksheet("Provider Analysis"); provider.addRow(["Provider", "Gross charge"]); input.analysis.providerConcentration.forEach((item) => provider.addRow([item.provider, Number(item.grossCharge) / 100])); moneyColumn(provider, 2);
  const service = workbook.addWorksheet("Service Line"); service.addRow(["Service line", "Gross charge"]); input.analysis.serviceLineConcentration.forEach((item) => service.addRow([item.serviceLine, Number(item.grossCharge) / 100])); moneyColumn(service, 2);
  const curves = workbook.addWorksheet("Recovery Analysis"); curves.addRows([["Age bucket", "Configured recovery rate", "A/R balance", "Expected recovery"], ["0-30", null], ["31-60", null], ["61-90", null], ["91-120", null], ["121+", null]]); ["0-30", "31-60", "61-90", "91-120", "121+"].forEach((bucket, index) => { const row = index + 2; curves.getCell(`B${row}`).value = input.recoveryRates?.[bucket] ?? null; curves.getCell(`C${row}`).value = { formula: `SUMIFS('AR Aging'!J:J,'AR Aging'!H:H,A${row},'AR Aging'!K:K,\"Active\")` }; curves.getCell(`D${row}`).value = { formula: `B${row}*C${row}` }; }); curves.getColumn(2).numFmt = "0.0%"; moneyColumn(curves, 3); moneyColumn(curves, 4);
  const assumptions = workbook.addWorksheet("Assumptions"); assumptions.addRows([["Method profile", input.methodId], ["Version", input.methodVersion], ["Professional materiality", "Unset until approved"], ["Recovery methodology", "Method-profile configured; approval-bound"], ["Authoritative editable recovery rates", "Recovery Analysis!B2:B6"], ["Important", "Changing the workbook assumptions does not approve a platform Method Profile or release a client work product."]]);
  const recon = workbook.addWorksheet("Reconciliation"); recon.addRow(["Control", "Left total", "Right total", "Difference", "Arithmetic status", "Materiality", "Evidence"]); input.reconciliations.forEach((r) => { const row = recon.addRow([r.label, Number(r.leftTotal) / 100, Number(r.rightTotal) / 100, null, r.arithmeticStatus, r.materialityStatus, r.evidence.join("; ")]); row.getCell(4).value = { formula: `B${row.number}-C${row.number}` }; }); moneyColumn(recon, 2); moneyColumn(recon, 3); moneyColumn(recon, 4);
  const findings = workbook.addWorksheet("Findings"); findings.addRow(["Status", "Title", "Detail", "Evidence"]); input.findings.forEach((f) => findings.addRow([f.status, f.title, f.detail, f.references.join("; ")]));
  const trace = workbook.addWorksheet("Source Trace"); trace.addRow(["Source file", "File hash", "Source row", "Record type", "Record ID"]); for (const claim of input.deal.claims) trace.addRow([claim.lineage.sourceFileName, claim.lineage.sourceFileHash, claim.lineage.sourceRowId, "Claim", `${claim.id}:v${claim.version}`]); for (const event of input.deal.cashEvents) trace.addRow([event.lineage.sourceFileName, event.lineage.sourceFileHash, event.lineage.sourceRowId, "CashEvent", event.id]); for (const event of input.deal.adjustmentEvents) trace.addRow([event.lineage.sourceFileName, event.lineage.sourceFileHash, event.lineage.sourceRowId, "AdjustmentEvent", event.id]); for (const ar of input.deal.receivables) trace.addRow([ar.lineage.sourceFileName, ar.lineage.sourceFileHash, ar.lineage.sourceRowId, "Receivable", ar.id]); for (const gl of input.deal.glRecords) trace.addRow([gl.lineage.sourceFileName, gl.lineage.sourceFileHash, gl.lineage.sourceRowId, "GLRecord", gl.id]);
  style(workbook); return Buffer.from(await workbook.xlsx.writeBuffer());
}
export function workbookNarrative(analysis: QorAnalysis): string { return `Observed cash is ${money(analysis.observedCash)}; expected remaining cash is ${money(analysis.expectedRemainingCash)} and remains distinct from observed cash.`; }
